# SYSTEM
url: "https://hci-calendar.github.io"
baseurl: "" # the subpath of your site, e.g. /blog

# SITE
title: HCI Calendar
copyright: "Copyright (C) HCI Calendar. All rights reserved."

# ALL Calendar Links
links:
  -
    name: HCI
    link: /
  -
    name: VR
    link: /vr/
#  -
#    name: CG
#    link: /cg/

# SEO
google_analytics: UA-80597905-1

# INCLUDE PAGES
include: ['_pages']

# SETTING
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-redirect-from
